name: 'Setup Rust Toolchain'
description: 'Install Rust toolchain with caching'

inputs:
  toolchain:
    description: 'Rust toolchain version (stable, nightly, or specific version)'
    required: false
    default: 'stable'
  components:
    description: 'Comma-separated list of components to install (e.g., rustfmt,clippy)'
    required: false
    default: ''
  targets:
    description: 'Comma-separated list of targets to install (e.g., x86_64-unknown-linux-musl)'
    required: false
    default: ''
  cache-key:
    description: 'Shared cache key for rust-cache'
    required: false
    default: 'rust-cache'

runs:
  using: 'composite'
  steps:
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}
